--------------------------------------------------------
--   Macrospace Optimization Schema Feb 04 2015---   
--------------------------------------------------------

CREATE TABLE MSO_DATA_REQ
(
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	START_PER_ID         NUMBER(5) NOT NULL ,
	END_PER_ID           NUMBER(5) NOT NULL ,
	MSO_DATA_REQ_DESCRIPTION VARCHAR2(100) NULL ,
	DATA_REQ_DATE        DATE NOT NULL ,
	RUN_DATE             DATE NULL ,
	CREATE_ID            VARCHAR2(20) NOT NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20),
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_DATA_REQ.MSO_DATA_REQ_ID IS 'Data Request ID';
COMMENT ON COLUMN MSO_DATA_REQ.START_PER_ID IS 'Starting Period ID';
COMMENT ON COLUMN MSO_DATA_REQ.END_PER_ID IS 'END Period ID';
COMMENT ON COLUMN MSO_DATA_REQ.MSO_DATA_REQ_DESCRIPTION IS 'MSO Data Request description';
COMMENT ON COLUMN MSO_DATA_REQ.DATA_REQ_DATE IS 'MSO Data Request Date';

ALTER TABLE MSO_DATA_REQ ADD CONSTRAINT  MSO_DATA_REQ_PK PRIMARY KEY (MSO_DATA_REQ_ID);
---------------------------------------------------
--   Table_Name:MSO_PROJ
-----------------------------------------------------
CREATE TABLE MSO_PROJ
(
	MSO_PROJ_ID          INTEGER NOT NULL ,
	PROJECT_NAME         VARCHAR2(50) NULL ,
	PROJECT_DESC         VARCHAR2(250) NULL ,
	PROJECT_STATUS       VARCHAR2(15) NULL ,
	PROJECT_TYPE         CHAR(18) NULL ,
	ACTIVE_IND           VARCHAR2(1) NULL ,
	PROJECT_DUE_DATE     DATE NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_PROJ.MSO_PROJ_ID IS 'Project ID';
COMMENT ON COLUMN MSO_PROJ.PROJECT_NAME IS 'Project Name';
COMMENT ON COLUMN MSO_PROJ.PROJECT_DESC IS 'Project Description';
COMMENT ON COLUMN MSO_PROJ.PROJECT_STATUS IS 'Project Status';
COMMENT ON COLUMN MSO_PROJ.ACTIVE_IND IS 'Active Indicator';
COMMENT ON COLUMN MSO_PROJ.PROJECT_DUE_DATE IS 'Project Due Date';

ALTER TABLE MSO_PROJ ADD CONSTRAINT  MSO_PROJ_PK PRIMARY KEY (MSO_PROJ_ID);
---------------------------------------------------
--   Table_Name:MSO_PROJ_DATA_REQ
-----------------------------------------------------
CREATE TABLE MSO_PROJ_DATA_REQ
(
	MSO_PROJ_DATA_REQ_ID INTEGER NOT NULL ,
	MSO_PROJ_ID          INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
	
);

COMMENT ON COLUMN MSO_PROJ_DATA_REQ.MSO_PROJ_DATA_REQ_ID IS 'Project Data Request ID';
COMMENT ON COLUMN MSO_PROJ_DATA_REQ.MSO_DATA_REQ_ID IS 'Data Request ID';
COMMENT ON COLUMN MSO_PROJ_DATA_REQ.MSO_PROJ_ID IS 'Project ID';

ALTER TABLE MSO_PROJ_DATA_REQ ADD CONSTRAINT MSO_PROJ_DATA_REQ_PK PRIMARY KEY (MSO_PROJ_DATA_REQ_ID);
ALTER TABLE MSO_PROJ_DATA_REQ ADD CONSTRAINT MSO_PROJ_DATA_REQ_UK UNIQUE (MSO_PROJ_ID, MSO_DATA_REQ_ID);
---------------------------------------------------
--   Table_Name:MSO_EXCL_PERIOD
-----------------------------------------------------
CREATE TABLE MSO_EXCL_PERIOD
(
	EXCLUSION_PERIOD_ID  INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	EXCL_START_PERIOD_ID NUMBER(5) NOT NULL ,
	EXCL_END_PERIOD_ID   NUMBER(5) NOT NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
	);


ALTER TABLE MSO_EXCL_PERIOD ADD CONSTRAINT  EXCLUSION_PERIOD_ID_PK PRIMARY KEY (EXCLUSION_PERIOD_ID);
ALTER TABLE MSO_EXCL_PERIOD ADD CONSTRAINT  EXCLUSION_PERIOD_ID_UK UNIQUE (MSO_DATA_REQ_ID, EXCL_START_PERIOD_ID, EXCL_END_PERIOD_ID);

---------------------------------------------------
--   Table_Name:MSO_EXCL_DATA_OPSTUDY
-----------------------------------------------------
CREATE TABLE MSO_EXCL_DATA_OPSTUDY
(
	MSO_EXCL_OPSTUDY_ID  INTEGER NOT NULL ,
	OPSTUDY_ID           NUMBER(7) NULL ,
        FROM_DTTM            TIMESTAMP,
        TO_DTTM              TIMESTAMP,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

ALTER TABLE MSO_EXCL_DATA_OPSTUDY ADD CONSTRAINT  MSO_EXCL_DATA_OPSTUDY_PK PRIMARY KEY (MSO_EXCL_OPSTUDY_ID);
ALTER TABLE MSO_EXCL_DATA_OPSTUDY ADD CONSTRAINT  MSO_EXCL_DATA_OPSTUDY_UK UNIQUE (OPSTUDY_ID,FROM_DTTM,TO_DTTM);
--------------------------------------------------
--   Table_Name:MSO_EXCL_DATA_STORE
-----------------------------------------------------
CREATE TABLE MSO_EXCL_DATA_STORE
(
	MSO_EXCL_STORE_ID    INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);


ALTER TABLE MSO_EXCL_DATA_STORE ADD CONSTRAINT  MSO_EXCL_DATA_STORE_PK PRIMARY KEY (MSO_EXCL_STORE_ID);
ALTER TABLE MSO_EXCL_DATA_STORE ADD CONSTRAINT  MSO_EXCL_DATA_STORE_UK UNIQUE (MSO_DATA_REQ_ID,LOC_ID);
--------------------------------------------------
--   Table_Name:MSO_EXCL_DATA_DEPT
-----------------------------------------------------
CREATE TABLE MSO_EXCL_DATA_DEPT
(
	MSO_EXCL_DEPT_ID     INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
        FROM_DTTM            TIMESTAMP,
        TO_DTTM              TIMESTAMP,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

ALTER TABLE MSO_EXCL_DATA_DEPT 	ADD CONSTRAINT  MSO_EXCL_DATA_DEPT_PK PRIMARY KEY (MSO_EXCL_DEPT_ID);
ALTER TABLE MSO_EXCL_DATA_DEPT 	ADD CONSTRAINT  MSO_EXCL_DATA_DEPT_UK UNIQUE (DEPARTMENT_ID,FROM_DTTM,TO_DTTM);
--------------------------------------------------
--   Table_Name:MSO_SHARD_FIX_MASTER_RULES
-----------------------------------------------------
CREATE TABLE MSO_SHARD_FIX_MASTER_RULES
(
	SHARED_FIX_MAST_RULE_ID INTEGER NOT NULL ,
	RULE_SETUP_MASTER_ID INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	ADJ_DEPT_ID          INTEGER NULL ,
	FROM_DTTM            TIMESTAMP,
	TO_DTTM              TIMESTAMP NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_SHARD_FIX_MASTER_RULES.SHARED_FIX_MAST_RULE_ID IS 'Master Rules : Shared Fixure ID : Surrogate Key';
COMMENT ON COLUMN MSO_SHARD_FIX_MASTER_RULES.REMARKS IS 'Remarks';
COMMENT ON COLUMN MSO_SHARD_FIX_MASTER_RULES.FROM_DTTM IS 'Valid From Date (Timestamp)';
COMMENT ON COLUMN MSO_SHARD_FIX_MASTER_RULES.TO_DTTM IS 'Valid unti To date (Timestamp)';
COMMENT ON COLUMN MSO_SHARD_FIX_MASTER_RULES.ADJ_DEPT_ID IS 'Adjacent Department ';
COMMENT ON COLUMN MSO_SHARD_FIX_MASTER_RULES.DEPARTMENT_ID IS 'Department ID';


ALTER TABLE MSO_SHARD_FIX_MASTER_RULES ADD CONSTRAINT  MSO_SHARD_FIX_MASTER_RULES_PK PRIMARY KEY (SHARED_FIX_MAST_RULE_ID);
ALTER TABLE MSO_SHARD_FIX_MASTER_RULES ADD CONSTRAINT  MSO_SHARD_FIX_MASTER_RULES_UK UNIQUE (RULE_SETUP_MASTER_ID,DEPARTMENT_ID,ADJ_DEPT_ID, FROM_DTTM, TO_DTTM);
--------------------------------------------------
--   Table_Name:MSO_RULE_SETUP_MASTER
-----------------------------------------------------
CREATE TABLE MSO_RULE_SETUP_MASTER
(
	RULE_SETUP_MASTER_ID INTEGER NOT NULL ,
	RULE_SETUP_CODE      CHAR(18) NULL ,
	RULE_SETUP_DESCRIPTION VARCHAR(100),
	RULES_CATEGORY       CHAR(18) NOT NULL ,
	FROM_DTTM            TIMESTAMP NULL ,
	TO_DTTM              TIMESTAMP NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_RULE_SETUP_MASTER.RULE_SETUP_MASTER_ID IS 'Master Rule Surrogate Key';
COMMENT ON COLUMN MSO_RULE_SETUP_MASTER.RULES_CATEGORY IS 'Category of Rules';
COMMENT ON COLUMN MSO_RULE_SETUP_MASTER.REMARKS IS 'Remarks';
COMMENT ON COLUMN MSO_RULE_SETUP_MASTER.FROM_DTTM IS 'Valid From Date (Timestamp)';
COMMENT ON COLUMN MSO_RULE_SETUP_MASTER.TO_DTTM IS 'Valid unti To date (Timestamp)';

ALTER TABLE MSO_RULE_SETUP_MASTER ADD CONSTRAINT  MSO_RULE_SETUP_MASTER_PK PRIMARY KEY (RULE_SETUP_MASTER_ID);
--------------------------------------------------
--   Table_Name:MSO_PROJECT_RULE_SETUP_ASSOC
-----------------------------------------------------
CREATE TABLE MSO_PROJECT_RULE_SETUP_ASSOC
(
	PROJ_RULE_SETUP_ID   INTEGER NOT NULL ,
	RULE_SETUP_MASTER_ID INTEGER NOT NULL ,
	MSO_PROJ_ID          INTEGER NOT NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_PROJECT_RULE_SETUP_ASSOC.PROJ_RULE_SETUP_ID IS ' Rule Setup Id Surrogate Key';
COMMENT ON COLUMN MSO_PROJECT_RULE_SETUP_ASSOC.REMARKS IS 'Remarks';
COMMENT ON COLUMN MSO_PROJECT_RULE_SETUP_ASSOC.MSO_PROJ_ID IS 'Project ID';

ALTER TABLE MSO_PROJECT_RULE_SETUP_ASSOC ADD CONSTRAINT  MSO_PROJECT_RULE_SETUP_PK PRIMARY KEY (PROJ_RULE_SETUP_ID);
ALTER TABLE MSO_PROJECT_RULE_SETUP_ASSOC ADD CONSTRAINT  MSO_PROJECT_RULE_SETUP_UK UNIQUE (RULE_SETUP_MASTER_ID,MSO_PROJ_ID);
--------------------------------------------------
--   Table_Name:MSO_OPTIMIZER_RESULTS
-----------------------------------------------------
CREATE TABLE MSO_OPTIMIZER_RESULTS
(
	OPTIMIZE_RESULT_ID   INTEGER NOT NULL ,
	INSTANCE_ID     INTEGER NOT NULL ,
	SOLUTION_ID          NUMBER(16) NULL ,
	FIXTURE_ID           INTEGER NULL ,
	CURR_IND             CHAR(1) NULL ,
	FOOTAGE              NUMBER(16,0) NULL ,
	TOT_OPTIMAL_BENIFIT  NUMBER(16) NULL ,
	OPTIMAL_SPACE        NUMBER(16) NULL ,
	OPTIMAL_SALES        NUMBER(16,2) NULL ,
	OPTIMAL_MARGIN       NUMBER(3) NULL ,
	OPTIMAL_UNIT         NUMBER(16) NULL ,
	PERCENTAGE_CHANGE    NUMBER(4) NULL ,
	VARIANCE             NUMBER(4) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

ALTER TABLE MSO_OPTIMIZER_RESULTS ADD CONSTRAINT  MSO_OPTIMIZER_RESULTS_PK PRIMARY KEY (OPTIMIZE_RESULT_ID);
ALTER TABLE MSO_OPTIMIZER_RESULTS ADD CONSTRAINT  MSO_OPTIMIZER_RESULTS_UK UNIQUE (INSTANCE_ID,SOLUTION_ID, FIXTURE_ID, CURR_IND);
--------------------------------------------------
--   Table_Name:MSO_DIM_KPI
-----------------------------------------------------
CREATE TABLE MSO_DIM_KPI
(
	KPI_ID               INTEGER NOT NULL ,
	KPI_TYPE             VARCHAR2(15) NULL ,
	KPI_CODE             VARCHAR2(15) NULL ,
	KPI_DESC             VARCHAR2(50) NOT NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_DIM_KPI.KPI_ID IS 'KPI ID - Primary Key from Dimension KPI';
COMMENT ON COLUMN MSO_DIM_KPI.KPI_TYPE IS 'KPI Type';
COMMENT ON COLUMN MSO_DIM_KPI.KPI_CODE IS 'KPI Code';
COMMENT ON COLUMN MSO_DIM_KPI.KPI_DESC IS 'KPI Description';


ALTER TABLE MSO_DIM_KPI ADD CONSTRAINT  MSO_DIM_KPI_PK PRIMARY KEY (KPI_ID);
--------------------------------------------------
--   Table_Name:MSO_PROJECT_STORE
-----------------------------------------------------
CREATE TABLE MSO_PROJECT_STORE
(
	PROJECT_STORE_ID     INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	MSO_PROJ_ID          INTEGER NOT NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL
);

COMMENT ON COLUMN MSO_PROJECT_STORE.PROJECT_STORE_ID IS 'Project STORE ID is surrogate Key';
COMMENT ON COLUMN MSO_PROJECT_STORE.MSO_PROJ_ID IS 'Project ID';
COMMENT ON COLUMN MSO_PROJECT_STORE.LOC_ID IS 'Location ID';


ALTER TABLE MSO_PROJECT_STORE ADD CONSTRAINT  MSO_PROJECT_STORE_PK PRIMARY KEY (PROJECT_STORE_ID);
ALTER TABLE MSO_PROJECT_STORE ADD CONSTRAINT  MSO_PROJECT_STORE_UK UNIQUE (LOC_ID, MSO_PROJ_ID);
--------------------------------------------------
--   Table_Name:MSO_USER_MASTER
-----------------------------------------------------
CREATE TABLE MSO_USER_MASTER
(
	MSO_USER_ID          VARCHAR2(20) NOT NULL ,
	USER_CODE            VARCHAR2(7) NULL ,
	USER_FIRST_NAME      VARCHAR(20) NULL ,
	USER_LAST_NAME       VARCHAR(20) NULL ,
	USER_ROLE                 VARCHAR(10) NULL ,
	FROM_DTTM            TIMESTAMP NULL ,
	TO_DTTM              TIMESTAMP NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_USER_MASTER.MSO_USER_ID IS 'MSO_USER_ID as surrogate Key';
COMMENT ON COLUMN MSO_USER_MASTER.FROM_DTTM IS 'Valid from From Date in Timestamp';
COMMENT ON COLUMN MSO_USER_MASTER.TO_DTTM IS 'Valid Until To Date Timestamp';
COMMENT ON COLUMN MSO_USER_MASTER.USER_FIRST_NAME IS 'User First Name';
COMMENT ON COLUMN MSO_USER_MASTER.USER_LAST_NAME IS 'User Last Name';
COMMENT ON COLUMN MSO_USER_MASTER.USER_CODE IS 'User Code';

ALTER TABLE MSO_USER_MASTER ADD CONSTRAINT  MSO_USER_MASTER_PK PRIMARY KEY (MSO_USER_ID);
--------------------------------------------------
--   Table_Name:MSO_SEQ_MASTER_RULES
-----------------------------------------------------
CREATE TABLE MSO_SEQ_MASTER_RULES
(
	MAST_SEQ_RULE_ID     INTEGER NOT NULL ,
	RULE_SETUP_MASTER_ID INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	RANK                 INTEGER NOT NULL ,
	FROM_DTTM            TIMESTAMP NULL ,
	TO_DTTM              TIMESTAMP NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_SEQ_MASTER_RULES.MAST_SEQ_RULE_ID IS 'Master Rule - Seq Rule : Surrogate Key';
COMMENT ON COLUMN MSO_SEQ_MASTER_RULES.RANK IS 'RANK';
COMMENT ON COLUMN MSO_SEQ_MASTER_RULES.REMARKS IS 'Remarks';
COMMENT ON COLUMN MSO_SEQ_MASTER_RULES.FROM_DTTM IS 'Valid from From Date in Timestamp';
COMMENT ON COLUMN MSO_SEQ_MASTER_RULES.TO_DTTM IS 'Valid Until To Date Timestamp';
COMMENT ON COLUMN MSO_SEQ_MASTER_RULES.DEPARTMENT_ID IS 'Department ID';
COMMENT ON COLUMN MSO_SEQ_MASTER_RULES.RULE_SETUP_MASTER_ID IS 'Rule Setup Master ID';


ALTER TABLE MSO_SEQ_MASTER_RULES ADD CONSTRAINT  MSO_SEQ_MASTER_RULES_PK PRIMARY KEY (MAST_SEQ_RULE_ID);
ALTER TABLE MSO_SEQ_MASTER_RULES ADD CONSTRAINT  MSO_SEQ_MASTER_RULES_UK UNIQUE (RULE_SETUP_MASTER_ID,DEPARTMENT_ID,FROM_DTTM, TO_DTTM);
--------------------------------------------------
--   Table_Name:MSO_SEGMENT_MASTER
-----------------------------------------------------
CREATE TABLE MSO_SEGMENT_MASTER
(
	SEGMENT_ID           INTEGER NOT NULL ,
	SEGMENT_NAME         VARCHAR2(50) NULL ,
	FROM_DTTM            TIMESTAMP NULL ,
	TO_DTTM              TIMESTAMP NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

ALTER TABLE MSO_SEGMENT_MASTER 	ADD CONSTRAINT MSO_SEGMENT_MASTER_PK PRIMARY KEY (SEGMENT_ID);
--------------------------------------------------
--   Table_Name:MSO_BATCH_REQ_PHASE_MASTER
-----------------------------------------------------

CREATE TABLE MSO_BATCH_REQ_PHASE_MASTER
(
	MSO_BATCH_REQ_PHASE_ID INTEGER NOT NULL ,
	PHASE_CODE           VARCHAR2(18) NULL ,
	PHASE_DESCRIPTION    VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_BATCH_REQ_PHASE_MASTER.MSO_BATCH_REQ_PHASE_ID IS 'Batch request Phase ID';
COMMENT ON COLUMN MSO_BATCH_REQ_PHASE_MASTER.PHASE_CODE IS 'PHASE_CODE';
COMMENT ON COLUMN MSO_BATCH_REQ_PHASE_MASTER.PHASE_DESCRIPTION IS 'PHASE_DESCRIPTION';

ALTER TABLE MSO_BATCH_REQ_PHASE_MASTER ADD CONSTRAINT  MSO_BATCH_REQ_PHASE_MASTER_PK PRIMARY KEY (MSO_BATCH_REQ_PHASE_ID);
--------------------------------------------------
--   Table_Name:MSO_INSTANCE
-----------------------------------------------------

CREATE TABLE MSO_INSTANCE
(
	INSTANCE_ID          INTEGER NOT NULL ,
	PROJ_RULE_SETUP_ID   INTEGER NOT NULL ,
	MSO_PROJ_DATA_REQ_ID INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	KPI_ID               INTEGER NOT NULL ,
	ZONE_NAME            VARCHAR2(25) NULL ,
        INSTANCE_DESC        VARCHAR2(100),
	OPTIMIZATION_TYPE    CHAR(18) NULL ,
        ADDITIONAL_SPACE     NUMBER(18),
        ABSOLUTE_SPACE       NUMBER(18),
        ALLOW_PTB            CHAR(1),
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_INSTANCE.INSTANCE_ID IS 'Instance ID - Surrogate Key';
COMMENT ON COLUMN MSO_INSTANCE.MSO_PROJ_DATA_REQ_ID IS 'Project Data Request ID';
COMMENT ON COLUMN MSO_INSTANCE.OPTIMIZATION_TYPE IS 'Optimization Type';
COMMENT ON COLUMN MSO_INSTANCE.KPI_ID IS 'KPI ID - Primary Key from Dimension KPI';
COMMENT ON COLUMN MSO_INSTANCE.PROJ_RULE_SETUP_ID IS 'Project Rule Setup Id';


ALTER TABLE MSO_INSTANCE ADD CONSTRAINT  MSO_INSTANCE_PK PRIMARY KEY (INSTANCE_ID);
ALTER TABLE MSO_INSTANCE ADD CONSTRAINT  MSO_INSTANCE_UK UNIQUE (PROJ_RULE_SETUP_ID,MSO_PROJ_DATA_REQ_ID,LOC_ID,KPI_ID);
--------------------------------------------------
--   Table_Name:MSO_STATUS_MASTER
-----------------------------------------------------

CREATE TABLE MSO_STATUS_MASTER
(
	STATUS_ID            INTEGER NOT NULL ,
	STATUS_CODE          VARCHAR2(15) NULL ,
	STATUS_DESCRIPTION   VARCHAR2(50) NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);


ALTER TABLE MSO_STATUS_MASTER ADD CONSTRAINT  MSO_STATUS_MASTER_PK PRIMARY KEY (STATUS_ID);
ALTER TABLE MSO_STATUS_MASTER ADD CONSTRAINT  MSO_STATUS_MASTER_UK UNIQUE (STATUS_CODE);

--------------------------------------------------
--   Table_Name:MSO_BATCH_WRAPPER_DETL
-----------------------------------------------------
CREATE TABLE MSO_BATCH_WRAPPER_DETL
(
	MSO_BATCH_WRAP_DETL_ID INTEGER NOT NULL ,
	MSO_DREQ_INSTANCE_ID INTEGER NULL ,
	ENTITY_TYPE          VARCHAR2(18) NULL ,
	MSO_BATCH_REQ_PHASE_ID INTEGER NOT NULL ,
	STATUS_ID            INTEGER NOT NULL ,
	REASON_CODE_DESC     VARCHAR2(100) NULL ,
	COMPLETION_DTTM      TIMESTAMP NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_BATCH_WRAPPER_DETL.MSO_BATCH_WRAP_DETL_ID IS 'MSO Batch Wrapper Detail ID';
COMMENT ON COLUMN MSO_BATCH_WRAPPER_DETL.MSO_DREQ_INSTANCE_ID IS 'MSO Data Request Instance ID';
COMMENT ON COLUMN MSO_BATCH_WRAPPER_DETL.ENTITY_TYPE IS 'Entity Type :EX : INSTANCE or DATA REQUEST';
COMMENT ON COLUMN MSO_BATCH_WRAPPER_DETL.MSO_BATCH_REQ_PHASE_ID IS 'Data Request Phases  ';

ALTER TABLE MSO_BATCH_WRAPPER_DETL ADD CONSTRAINT  MSO_BATCH_WRAPPER_DETL_PK PRIMARY KEY (MSO_BATCH_WRAP_DETL_ID);
ALTER TABLE MSO_BATCH_WRAPPER_DETL ADD CONSTRAINT  MSO_BATCH_WRAPPER_DETL_UK UNIQUE (MSO_DREQ_INSTANCE_ID,MSO_BATCH_REQ_PHASE_ID,STATUS_ID );

--------------------------------------------------
--   Table_Name:MSO_STORE_FIXT_RULES
-----------------------------------------------------
CREATE TABLE MSO_STORE_FIXT_RULES
(
	FIX_STORE_RULE_ID    INTEGER NOT NULL ,
	FIXTURE_ID           INTEGER NOT NULL ,
	INSTANCE_ID              INTEGER NOT NULL ,
	FIXTURE_DESC         VARCHAR2(250) NULL ,
	FIXTURE_LENGTH       NUMBER(10) NULL ,
	FIXTURE_TYPE         VARCHAR2(15) NULL ,
	FIXTURE_HEIGHT       NUMBER(5) NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);


COMMENT ON COLUMN MSO_STORE_FIXT_RULES.FIX_STORE_RULE_ID IS 'Surrogate Key for fixture Rules for Projects or Project Instance';
COMMENT ON COLUMN MSO_STORE_FIXT_RULES.FIXTURE_ID IS 'Fixture ID';
COMMENT ON COLUMN MSO_STORE_FIXT_RULES.FIXTURE_DESC IS 'Fixture Desc';
COMMENT ON COLUMN MSO_STORE_FIXT_RULES.FIXTURE_LENGTH IS 'Fixture Length';
COMMENT ON COLUMN MSO_STORE_FIXT_RULES.FIXTURE_TYPE IS 'Fixture Type';
COMMENT ON COLUMN MSO_STORE_FIXT_RULES.FIXTURE_HEIGHT IS 'Fixture Height';
COMMENT ON COLUMN MSO_STORE_FIXT_RULES.REMARKS IS 'Remarks';
COMMENT ON COLUMN MSO_STORE_FIXT_RULES.INSTANCE_ID IS 'Instance ID';

ALTER TABLE MSO_STORE_FIXT_RULES ADD CONSTRAINT  MSO_STORE_FIXT_RULES_PK PRIMARY KEY (FIX_STORE_RULE_ID);
ALTER TABLE MSO_STORE_FIXT_RULES ADD CONSTRAINT  MSO_STORE_FIXT_RULES_UK UNIQUE (FIXTURE_ID,INSTANCE_ID);
--------------------------------------------------
--   Table_Name:MSO_DEPT_CONST_MASTER_RULES
-----------------------------------------------------
CREATE TABLE MSO_DEPT_CONST_MASTER_RULES
(
	DEPT_MAST_CONST_RULE_ID INTEGER NOT NULL ,
	RULE_SETUP_MASTER_ID INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	FLEXDOWNBY           INTEGER NULL ,
	BUTNOTBELOW          INTEGER NULL ,
	FLEXUPBY             INTEGER NULL ,
	BUTNOTABOVE          INTEGER NULL ,
	CONSTRAINTS_UNITS    VARCHAR2(30) NULL ,
	SPACE_INCREMENTS     INTEGER NULL ,
	OBEY_POG_LIMIT       CHAR(1) NULL ,
	OBEY_CFW             CHAR(1) NULL ,
	FROM_DTTM            TIMESTAMP NULL ,
	TO_DTTM              TIMESTAMP NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);


COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.DEPT_MAST_CONST_RULE_ID IS 'MASTER RULE : Department Constraint Rule ID';
COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.FLEXDOWNBY IS 'Flex Down By';
COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.CONSTRAINTS_UNITS IS 'Constraint Units in Number';
COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.SPACE_INCREMENTS IS 'Space Increments';
COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.REMARKS IS 'Remarks';
COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.FROM_DTTM IS 'Valid From In Timestamp';
COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.TO_DTTM IS 'Valid Until in Timestamp';
COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.DEPARTMENT_ID IS 'Department ID';
COMMENT ON COLUMN MSO_DEPT_CONST_MASTER_RULES.RULE_SETUP_MASTER_ID IS 'Rule Setup Master ID';

ALTER TABLE MSO_DEPT_CONST_MASTER_RULES ADD CONSTRAINT  MSO_DEPT_CONST_MASTER_RULES_PK PRIMARY KEY (DEPT_MAST_CONST_RULE_ID);
ALTER TABLE MSO_DEPT_CONST_MASTER_RULES ADD CONSTRAINT  MSO_DEPT_CONST_MASTER_RULES_UK UNIQUE (RULE_SETUP_MASTER_ID,DEPARTMENT_ID, FROM_DTTM, TO_DTTM);
--------------------------------------------------
--   Table_Name:MSO_STORE_DEPT_CONST_RULES
-----------------------------------------------------
CREATE TABLE MSO_STORE_DEPT_CONST_RULES
(
	DEPT_CONST_STORE_RULE_ID INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	INSTANCE_ID          INTEGER NOT NULL ,
	FLEXDOWNBY           INTEGER NULL ,
	BUTNOTBELOW          INTEGER NULL ,
	FLEXUPBY             INTEGER NULL ,
	BUTNOTABOVE          INTEGER NULL ,
	CONSTRAINTS_UNITS    VARCHAR2(30) NULL ,
	SPACE_INCREMENTS     INTEGER NULL ,
        OBEY_POG_LIMIT       CHAR(1) NULL ,
	OBEY_CFW             CHAR(1) NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_STORE_DEPT_CONST_RULES.DEPT_CONST_STORE_RULE_ID IS 'Surrogate Key for Project Department Constraint Rule';
COMMENT ON COLUMN MSO_STORE_DEPT_CONST_RULES.REMARKS IS 'Remarks';
COMMENT ON COLUMN MSO_STORE_DEPT_CONST_RULES.DEPARTMENT_ID IS 'Department ID';
COMMENT ON COLUMN MSO_STORE_DEPT_CONST_RULES.INSTANCE_ID IS 'Instance ID';



ALTER TABLE MSO_STORE_DEPT_CONST_RULES ADD CONSTRAINT  MSO_STORE_DEPT_CONST_RULES_PK PRIMARY KEY (DEPT_CONST_STORE_RULE_ID);
ALTER TABLE MSO_STORE_DEPT_CONST_RULES ADD CONSTRAINT  MSO_STORE_DEPT_CONST_RULES_UK UNIQUE (DEPARTMENT_ID,INSTANCE_ID);
--------------------------------------------------
--   Table_Name:MSO_STORE_SHARED_FIXT_RULES
-----------------------------------------------------
CREATE TABLE MSO_STORE_SHARED_FIXT_RULES
(
	SHARED_FIX_STORE_RULE_ID INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	ADJ_DEP_ID           INTEGER NOT NULL ,
	INSTANCE_ID          INTEGER NOT NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

ALTER TABLE MSO_INSTANCE_SHARED_FIXT_RULES ADD CONSTRAINT  MSO_INSTANCE_SHARED_FIXT_RULES_PK PRIMARY KEY (SHARED_FIX_INSTANCE_RULE_ID);
ALTER TABLE MSO_INSTANCE_SHARED_FIXT_RULES ADD CONSTRAINT  MSO_INSTANCE_SHARED_FIXT_RULES_UK UNIQUE (DEPARTMENT_ID,ADJ_DEP_ID,INSTANCE_ID);

COMMENT ON COLUMN MSO_INSTANCE_SHARED_FIXT_RULES.SHARED_FIX_INSTANCE_RULE_ID IS 'Shared Fixture Store Rule Id  Surrogate Key';
COMMENT ON COLUMN MSO_INSTANCE_SHARED_FIXT_RULES.DEPARTMENT_ID  IS 'DEPARTMENT ID ';
COMMENT ON COLUMN MSO_INSTANCE_SHARED_FIXT_RULES.ADJ_DEP_ID  IS 'Adjacent Department Id';
COMMENT ON COLUMN MSO_INSTANCE_SHARED_FIXT_RULES.INSTANCE_ID  IS 'Instance ID';

--------------------------------------------------
--   Table_Name:MSO_STORE_FIXT_COMPBTY
-----------------------------------------------------
CREATE TABLE MSO_STORE_FIXT_COMPBTY
(
	STORE_FIX_COMPBTY_RULE_ID INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	MAND_FIXTURE_ID      INTEGER NOT NULL ,
	FORBID_FIXTURE_ID    INTEGER NOT NULL ,
	INSTANCE_ID          INTEGER NOT NULL ,
	REMARKS              VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_STORE_FIXT_COMPBTY.STORE_FIX_COMPBTY_RULE_ID IS 'Surrogate Key Compatiability Rule ID';
COMMENT ON COLUMN MSO_STORE_FIXT_COMPBTY.REMARKS IS 'Remarks';
COMMENT ON COLUMN MSO_STORE_FIXT_COMPBTY.MAND_FIXTURE_ID IS 'Mandatory Fixture ID';
COMMENT ON COLUMN MSO_STORE_FIXT_COMPBTY.FORBID_FIXTURE_ID IS 'Forbidden Fixture ID';
COMMENT ON COLUMN MSO_STORE_FIXT_COMPBTY.DEPARTMENT_ID IS 'Department ID';
COMMENT ON COLUMN MSO_STORE_FIXT_COMPBTY.INSTANCE_ID IS 'Instance ID';


ALTER TABLE MSO_STORE_FIXT_COMPBTY ADD CONSTRAINT  MSO_STORE_FIXT_COMPBTY_PK PRIMARY KEY (STORE_FIX_COMPBTY_RULE_ID);
ALTER TABLE MSO_STORE_FIXT_COMPBTY ADD CONSTRAINT  MSO_STORE_FIXT_COMPBTY_UK UNIQUE (DEPARTMENT_ID,MAND_FIXTURE_ID,FORBID_FIXTURE_ID,INSTANCE_ID);

--------------------------------------------------
--   Table_Name:MSO_STORE_PRODUCTIVITY_MAP
-----------------------------------------------------
CREATE TABLE MSO_STORE_PRODUCTIVITY_MAP
(
	MSO_STORE_PRODUCTIVITY_MAP_ID   INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	ADJ_QUANTILE         NUMBER(10) NULL ,
	RAW_QUANTILE         NUMBER(10) NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);


COMMENT ON COLUMN MSO_STORE_PRODUCTIVITY_MAP.MSO_DATA_REQ_ID IS 'MSO_DATA_REQ_ID';
COMMENT ON COLUMN MSO_STORE_PRODUCTIVITY_MAP.LOC_ID IS 'LOC_ID';
ALTER TABLE MSO_STORE_PRODUCTIVITY_MAP ADD CONSTRAINT  MSO_STORE_PRODUCT_MAP_PK PRIMARY KEY (MSO_STORE_PRODUCTIVITY_MAP_ID);
ALTER TABLE MSO_STORE_PRODUCTIVITY_MAP ADD CONSTRAINT  MSO_STORE_PRODUCT_MAP_UK UNIQUE (MSO_DATA_REQ_ID,LOC_ID);
--------------------------------------------------
--   Table_Name:MSO_FCT_FOOTAGE_BENEFIT_STR_DE
-----------------------------------------------------
CREATE TABLE MSO_FCT_FOOTAGE_BENEFIT_STR_DE
(
	FCT_FTAGE_BEN_STR_DEP_ID INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	PLANO_SIZE           NUMBER(6,0) NULL ,
	WEEKS_COUNT          NUMBER(6) NULL ,
	AVG_WEEKLY_SALES_UNIT NUMBER(10,2) NULL ,
	AVG_WEEKLY_SALES_DOLLAR NUMERIC(16,2) NULL ,
	AVG_WEEKLY_GROSS_MARGIN NUMERIC(12,0) NULL ,
	CURR_IND             CHAR(1) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);


COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.FCT_FTAGE_BEN_STR_DEP_ID IS 'Surrogate Key FCT_FTAGE_BEN_STR_DEP_ID';
COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.MSO_DATA_REQ_ID IS 'Data Request ID';
COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.DEPARTMENT_ID IS 'Department ID';
COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.LOC_ID IS 'Location ID';
COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.PLANO_SIZE IS 'Plano Size';
COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.WEEKS_COUNT IS 'Count of Weeks';
COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.AVG_WEEKLY_SALES_UNIT IS 'Average Weekly Sales Unit';
COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.AVG_WEEKLY_SALES_DOLLAR IS 'Average Weekly Sales Dollar';
COMMENT ON COLUMN MSO_FCT_FOOTAGE_BENEFIT_STR_DE.AVG_WEEKLY_GROSS_MARGIN IS 'Average Weekly Gross Margin';

ALTER TABLE MSO_FCT_FOOTAGE_BENEFIT_STR_DE ADD CONSTRAINT  MSO_FCT_FOOTAGE_BENEFIT_STR_PK PRIMARY KEY (FCT_FTAGE_BEN_STR_DEP_ID);
ALTER TABLE MSO_FCT_FOOTAGE_BENEFIT_STR_DE ADD CONSTRAINT  MSO_FCT_FOOTAGE_BENEFIT_STR_UK UNIQUE (MSO_DATA_REQ_ID,DEPARTMENT_ID,LOC_ID,PLANO_SIZE);
--------------------------------------------------
--   Table_Name:MSO_FCT_CLS_ARR_OPS_DEPT
-----------------------------------------------------
CREATE TABLE MSO_FCT_CLS_ARR_OPS_DEPT
(
	FCT_CLS_ARR_ID       INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
        LOC_ID               INTEGER NOT NULL,
	OPS_ID               NUMBER(6,0) NULL ,
	TOT_52_WEEK_SALES_UNIT NUMBER(16) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);


COMMENT ON COLUMN MSO_FCT_CLS_ARR_OPS_DEPT.FCT_CLS_ARR_ID IS 'Surrogate Key FCT_CLS_ARR_ID';
COMMENT ON COLUMN MSO_FCT_CLS_ARR_OPS_DEPT.MSO_DATA_REQ_ID IS 'Data Request ID';
COMMENT ON COLUMN MSO_FCT_CLS_ARR_OPS_DEPT.OPS_ID IS 'Opstudy ID';
COMMENT ON COLUMN MSO_FCT_CLS_ARR_OPS_DEPT.TOT_52_WEEK_SALES_UNIT IS 'Total Sales Unit 52 Week';

ALTER TABLE MSO_FCT_CLS_ARR_OPS_DEPT ADD CONSTRAINT  MSO_FCT_CLS_ARR_OPS_DEPT_PK PRIMARY KEY (FCT_CLS_ARR_ID);
ALTER TABLE MSO_FCT_CLS_ARR_OPS_DEPT ADD CONSTRAINT  MSO_FCT_CLS_ARR_OPS_DEPT_UK UNIQUE (MSO_DATA_REQ_ID,LOC_ID,OPS_ID);
--------------------------------------------------
--   Table_Name:MSO_FCT_SPACE_VOL_STR
-----------------------------------------------------
CREATE TABLE MSO_FCT_SPACE_VOL_STR
(
	FCT_SPACE_VOL_STR_ID INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	TOT_WEEKLY_SALES_UNIT NUMBER(16) NULL ,
	TOT_WEEKLY_ITEM_FOOTAGE NUMBER(16,0) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_FCT_SPACE_VOL_STR.FCT_SPACE_VOL_STR_ID IS 'Surrogate Key FCT_SPACE_VOL_STR_ID';
COMMENT ON COLUMN MSO_FCT_SPACE_VOL_STR.MSO_DATA_REQ_ID IS 'Data Request ID';
COMMENT ON COLUMN MSO_FCT_SPACE_VOL_STR.LOC_ID IS 'Location ID';
COMMENT ON COLUMN MSO_FCT_SPACE_VOL_STR.TOT_WEEKLY_SALES_UNIT IS 'Total Weekly Sales Unit';

ALTER TABLE MSO_FCT_SPACE_VOL_STR ADD CONSTRAINT  MSO_FCT_SPACE_VOL_STR_PK PRIMARY KEY (FCT_SPACE_VOL_STR_ID);
ALTER TABLE MSO_FCT_SPACE_VOL_STR ADD CONSTRAINT  MSO_FCT_SPACE_VOL_STR_UK UNIQUE (MSO_DATA_REQ_ID,LOC_ID );
--------------------------------------------------
--   Table_Name:MSO_STORE_TREND
-----------------------------------------------------
CREATE TABLE MSO_STORE_TREND
(
	MSO_STORE_TREND_ID   INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	POG_5                NUMBER(16) NULL ,
	POG_95               NUMBER(16) NULL ,
	ALPHA_SCALED_UNITS   NUMBER(16) NULL ,
	BETA_UNITS           NUMBER(16) NULL ,
	CURVE_FIT_QLTY_UNITS NUMBER(10) NULL ,
	ALPHA_SCALED_SALES   NUMBER(16,2) NULL ,
	BETA_SALES           NUMBER(16,2) NULL ,
	CURVE_FIT_QLTY_SALES NUMBER(16,2) NULL ,
	ALPHA_SCALED_GM      NUMBER(16,2) NULL ,
	BETA_GM              NUMBER(16,2) NULL ,
	CURVE_FIT_QLTY_GM    NUMBER(16,2) NULL ,
	ALPHA_SCALED_FUTURE  NUMBER(16,2) NULL ,
	BETA_FUTURE          NUMBER(16,2) NULL ,
	CURVE_FIT_QLTY_FUTURE NUMBER(16,2) NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_STORE_TREND.MSO_STORE_TREND_ID IS 'Surrogate Key MSO_STORE_TREND_ID';
COMMENT ON COLUMN MSO_STORE_TREND.MSO_DATA_REQ_ID IS 'MSO_DATA_REQ_ID';
COMMENT ON COLUMN MSO_STORE_TREND.LOC_ID IS 'Location ID';
COMMENT ON COLUMN MSO_STORE_TREND.DEPARTMENT_ID IS 'Department ID';

ALTER TABLE MSO_STORE_TREND ADD CONSTRAINT  MSO_STORE_TREND_PK PRIMARY KEY (MSO_STORE_TREND_ID);
ALTER TABLE MSO_STORE_TREND ADD CONSTRAINT  MSO_STORE_TREND_UK UNIQUE (MSO_DATA_REQ_ID,LOC_ID,DEPARTMENT_ID);

--------------------------------------------------
--   Table_Name:MSO_HALLMARK_FOOTAGE
-----------------------------------------------------


CREATE TABLE MSO_HALLMARK_FOOTAGE
(
	HALLMARK_FOOTAGE_ID INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	FOOTAGE              NUMBER(10) NULL ,
	FROM_DTTM            TIMESTAMP NULL,
        TO_DTTM              TIMESTAMP NULL,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_HALLMARK_FOOTAGE.HALLMRK_FOOTAGE_ID IS 'Surrogate Key HALLMARK_FOOTAGE_ID';
COMMENT ON COLUMN MSO_HALLMARK_FOOTAGE.LOC_ID IS 'Location ID';
COMMENT ON COLUMN MSO_HALLMARK_FOOTAGE.FROM_DTTM  IS 'Valid From';
COMMENT ON COLUMN MSO_HALLMARK_FOOTAGE.TO_DTTM IS 'Valid Until';

ALTER TABLE MSO_HALLMARK_FOOTAGE ADD CONSTRAINT  MSO_HALLMARK_FOOTAGE_PK PRIMARY KEY (HALLMARK_FOOTAGE_ID);
ALTER TABLE MSO_HALLMARK_FOOTAGE ADD CONSTRAINT  MSO_HALLMARK_FOOTAGE_UK UNIQUE (LOC_ID,FROM_DTTM,TO_DTTM);
--------------------------------------------------
--   Table_Name:MSO_GROUP_TREND
-----------------------------------------------------
CREATE TABLE MSO_GROUP_TREND
(
	MSO_GROUP_TREND_ID   INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
	SEGMENT_ID           INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	ADJ_QUANTILE         NUMBER(10) NULL ,
	POG_5                NUMBER(16) NULL ,
	POG_95               NUMBER(16) NULL ,
	ALPHA_UNITS          NUMBER(16) NULL ,
	BETA_UNITS           NUMBER(16) NULL ,
	CURVE_FIT_QLTY_UNITS NUMBER(10) NULL ,
	ALPHA_SALES          NUMBER(16,2) NULL ,
	BETA_SALES           NUMBER(16,2) NULL ,
	CURVE_FIT_QLTY_SALES NUMBER(16,2) NULL ,
	ALPHA_GM             NUMBER(16,2) NULL ,
	BETA_GM              NUMBER(16,2) NULL ,
	CURVE_FIT_QLTY_GM    NUMBER(16,2) NULL ,
	ALPHA_FUTURE         NUMBER(16,2) NULL ,
	BETA_FUTURE          NUMBER(16,2) NULL ,
	CURVE_FIT_QLTY_FUTURE NUMBER(16,2) NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_GROUP_TREND.MSO_GROUP_TREND_ID IS 'Surrogate Key MSO_GROUP_TREND_ID';
COMMENT ON COLUMN MSO_GROUP_TREND.MSO_DATA_REQ_ID IS 'MSO_DATA_REQ_ID';
COMMENT ON COLUMN MSO_GROUP_TREND.SEGMENT_ID IS 'SEGMENT ID';
COMMENT ON COLUMN MSO_GROUP_TREND.DEPARTMENT_ID IS 'Department ID';
COMMENT ON COLUMN MSO_GROUP_TREND.ADJ_QUANTILE IS 'Adjacent Product Quantile';

ALTER TABLE MSO_GROUP_TREND ADD CONSTRAINT  MSO_GROUP_TREND_PK PRIMARY KEY (MSO_GROUP_TREND_ID);
ALTER TABLE MSO_GROUP_TREND ADD CONSTRAINT  MSO_GROUP_TREND_UK UNIQUE (MSO_DATA_REQ_ID,SEGMENT_ID,DEPARTMENT_ID);
--------------------------------------------------
--   Table_Name:MSO_INSTANCE_DEPT
-----------------------------------------------------
CREATE TABLE MSO_INSTANCE_DEPT
(
	INSTANCE_DEPT_ID     INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	INSTANCE_ID          INTEGER NOT NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_INSTANCE_DEPT.INSTANCE_DEPT_ID IS 'Surrogate Key INSTANCE_DEPT_ID';
COMMENT ON COLUMN MSO_INSTANCE_DEPT.DEPARTMENT_ID IS 'Department ID';
COMMENT ON COLUMN MSO_INSTANCE_DEPT.INSTANCE_ID IS 'Instance ID';

ALTER TABLE MSO_INSTANCE_DEPT ADD CONSTRAINT  MSO_INSTANCE_DEPT_PK PRIMARY KEY (INSTANCE_DEPT_ID);
ALTER TABLE MSO_INSTANCE_DEPT ADD CONSTRAINT  MSO_INSTANCE_DEPT_UK UNIQUE (DEPARTMENT_ID, INSTANCE_ID);




CREATE TABLE MSO_DATA_REQ_CFW
(
	MSO_DATA_REQ_CFW_ID  INTEGER NOT NULL ,
	MSO_DATA_REQ_ID      INTEGER NOT NULL ,
        SEGMENT_ID           INTEGER NOT NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	ADJ_QUANTILE         NUMBER(15) NULL ,
	COMMENTS             VARCHAR2(100) NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);

COMMENT ON COLUMN MSO_DATA_REQ_CFW.MSO_DATA_REQ_CFW_ID IS 'MSO_DATA_REQ_CFW_ID';
COMMENT ON COLUMN MSO_DATA_REQ_CFW.MSO_DATA_REQ_ID IS 'MSO DATA REQUEST ID';
COMMENT ON COLUMN MSO_DATA_REQ_CFW.DEPARTMENT_ID IS 'DEPARTMENT ID';
COMMENT ON COLUMN MSO_DATA_REQ_CFW.SEGMENT_ID IS 'SEGMENT_ID';


ALTER TABLE MSO_DATA_REQ_CFW ADD CONSTRAINT MSO_DATA_REQ_CFW_PK PRIMARY KEY (MSO_DATA_REQ_CFW_ID);
ALTER TABLE MSO_DATA_REQ_CFW ADD CONSTRAINT MSO_DATA_REQ_CFW_UK UNIQUE (MSO_DATA_REQ_ID,DEPARTMENT_ID,SEGMENT_ID);

CREATE TABLE MSO_STORE_SEGMENT_MAP
(
	STORE_SEGMENT_MAP_ID CHAR(18) NOT NULL ,
	SEGMENT_ID           INTEGER NOT NULL ,
	LOC_ID               NUMBER(7) NOT NULL ,
	PEER_GROUP_DESC      VARCHAR2(50) NULL ,
	METRO_MARKET_NAME_ACN VARCHAR2(28) NULL ,
	FROM_DTTM            TIMESTAMP NULL ,
	TO_DTTM              TIMESTAMP NULL ,
	CREATE_ID            VARCHAR2(18) NULL ,
	CREATE_DTTM          TIMESTAMP NULL 
);


COMMENT ON COLUMN MSO_STORE_SEGMENT_MAP.STORE_SEGMENT_MAP_ID IS 'STORE_SEGMENT_MAP_ID';
COMMENT ON COLUMN MSO_STORE_SEGMENT_MAP.SEGMENT_ID IS 'SEGMENT ID';
COMMENT ON COLUMN MSO_STORE_SEGMENT_MAP.LOC_ID IS 'LOCATION ID';

alter table mso_store_segment_map add constraint  mso_store_segment_map_pk primary key (store_segment_map_id);
ALTER TABLE MSO_STORE_SEGMENT_MAP ADD CONSTRAINT  MSO_STORE_SEGMENT_MAP_UK UNIQUE (SEGMENT_ID, LOC_ID);


CREATE TABLE MSO_OPTIMIZER_GEN2_RESULTS
(
	OPTIMIZE_GEN2_RESULT_ID INTEGER NOT NULL ,
	INSTANCE_ID          INTEGER NOT NULL ,
	SOLUTION_ID          NUMBER(16) NULL ,
	DEPARTMENT_ID        INTEGER NOT NULL ,
	FIXTURE_ID           INTEGER NULL ,
	PROFIT               NUMBER(16) NULL ,
	WEIGHT               NUMBER(16) NULL ,
	CREATE_ID            VARCHAR2(20) NULL ,
	CREATE_DTTM          TIMESTAMP NULL ,
	UPDATE_ID            VARCHAR2(20) NULL ,
	UPDATE_DTTM          TIMESTAMP NULL 
);

ALTER TABLE MSO_OPTIMIZER_GEN2_RESULTS ADD CONSTRAINT  MSO_OPT_GEN2_RESULTS_PK PRIMARY KEY (OPTIMIZE_GEN2_RESULT_ID);
ALTER TABLE MSO_OPTIMIZER_GEN2_RESULTS ADD CONSTRAINT  MSO_OPT_GEN2_RESULTS_UK UNIQUE (INSTANCE_ID,SOLUTION_ID,DEPARTMENT_ID,FIXTURE_ID);
