--------------------------------------------------------
--  Macro space Optimization - Sequences 
--------------------------------------------------------
/* Table_Name:MSO_DATA_REQ
    Column_name:MSO_DATA_REQ_ID
    Sequence to auto increment MSO_DATA_REQ_ID Column   */

CREATE SEQUENCE MSO_DATA_REQ_ID_SEQ
START WITH     10000000
INCREMENT BY   1
MAXVALUE 15000000
NOCACHE
NOCYCLE;

/*Table_Name:MSO_DATA_REQ_DETL
  Column_name:MSO_DATA_REQ_DETL_ID
  Sequence to autoincrement MSO_DATA_REQ_DETL_ID Column */

CREATE SEQUENCE MSO_DATA_REQ_DETL_ID_SEQ
START WITH     15000001
INCREMENT BY   1
MAXVALUE 20000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_MAST_DEPT_CONST_RULES
    Column_name:DEPT_MAST_CONST_RULE_ID
    Sequence to auto increment DEPT_MAST_CONST_RULE_ID Column   */
CREATE SEQUENCE DEPT_MAST_CONST_RULE_ID_SEQ
START WITH     20000001
INCREMENT BY   1
MAXVALUE 25000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_MAST_SEQ
    Column_name:MSO_SEQ_RULE_ID
    Sequence to auto increment MSO_SEQ_RULE_ID Column   */

CREATE SEQUENCE MSO_SEQ_RULE_ID_SEQ
START WITH     25000001
INCREMENT BY   1
MAXVALUE 30000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_MAST_SHARED_FIXT_RULES
    Column_name:SHARED_FIX_MAST_RULE_ID
    Sequence to auto increment SHARED_FIX_MAST_RULE_ID Column   */
CREATE SEQUENCE SHARED_FIX_MAST_RULE_ID_SEQ
START WITH     30000001
INCREMENT BY   1
MAXVALUE 35000000
NOCACHE
NOCYCLE;
/* Table_Name:MSO_INSTANCE
    Column_name:INSTANCE_ID
    Sequence to auto increment INSTANCE_ID Column   */

CREATE SEQUENCE INSTANCE_ID_SEQ
START WITH     35000001
INCREMENT BY   1
MAXVALUE 40000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_PROJECT_RULE_SETUP_ASSOC
    Column_name:PROJ_RULE_SETUP_ID
    Sequence to auto increment PROJ_RULE_SETUP_ID Column   */

CREATE SEQUENCE PROJ_RULE_SETUP_ID_SEQ
START WITH     40000001
INCREMENT BY   1
MAXVALUE 45000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_RULE_SETUP_MASTER
    Column_name:RULE_SETUP_MASTER_ID
    Sequence to auto increment RULE_SETUP_MASTER_ID Column   */

CREATE SEQUENCE RULE_SETUP_MASTER_ID_SEQ
START WITH     45000001
INCREMENT BY   1
MAXVALUE 50000000
NOCACHE
NOCYCLE;


/* Table_Name:MSO_PROJECT_STORE
    Column_name:PROJECT_STORE_ID
    Sequence to auto increment PROJECT_STORE_ID Column   */

CREATE SEQUENCE PROJECT_STORE_ID_SEQ
START WITH     50000001
INCREMENT BY   1
MAXVALUE 55000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_INSTANCE_DEPT
    Column_name:INSTANCE_DEPT_ID
    Sequence to auto increment INSTANCE_DEPT_ID Column   */

CREATE SEQUENCE INSTANCE_DEPT_ID_SEQ
START WITH     55000001
INCREMENT BY   1
MAXVALUE 60000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_EXCL_DATA_DEPT
    Column_name:MSO_EXCL_DEPT_ID
    Sequence to auto increment MSO_EXCL_DEPT_ID Column   */

CREATE SEQUENCE MSO_EXCL_DEPT_ID_SEQ
START WITH     60000001
INCREMENT BY   1
MAXVALUE 65000000
NOCACHE
NOCYCLE;


/* Table_Name:MSO_EXCL_DATA_OPSTUDY
    Column_name:MSO_EXCL_OPSTUDY_ID
    Sequence to auto increment MSO_EXCL_OPSTUDY_ID Column   */

CREATE SEQUENCE MSO_EXCL_OPSTUDY_ID_SEQ
START WITH    65000001 
INCREMENT BY   1
MAXVALUE 70000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_EXCL_DATA_STORE
    Column_name:MSO_EXCL_STORE_ID
    Sequence to auto increment MSO_EXCL_STORE_ID Column   */

CREATE SEQUENCE MSO_EXCL_STORE_ID_SEQ
START WITH     70000001
INCREMENT BY   1
MAXVALUE 75000000
NOCACHE
NOCYCLE;


/* Table_Name:MSO_EXCL_PERIOD
    Column_name:EXCLUSION_PERIOD_ID
    Sequence to auto increment EXCLUSION_PERIOD_ID Column   */

CREATE SEQUENCE EXCLUSION_PERIOD_ID_SEQ
START WITH     75000001
INCREMENT BY   1
MAXVALUE 80000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_BATCH_REQ_PHASE_MSTR
    Column_name:MSO_BATCH_REQ_PHASE_ID
    Sequence to auto increment MSO_BATCH_REQ_PHASE_ID Column   */

CREATE SEQUENCE MSO_BATCH_REQ_PHASE_ID_SEQ
START WITH     80000001
INCREMENT BY   1
MAXVALUE 85000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_DIM_KPI
    Column_name:KPI_ID
    Sequence to auto increment KPI_ID Column   */

CREATE SEQUENCE KPI_ID_SEQ
START WITH     85000001
INCREMENT BY   1
MAXVALUE 90000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_STORE_TREND
    Column_name:MSO_STORE_TREND_ID
    Sequence to auto increment MSO_STORE_TREND_ID Column   */

CREATE SEQUENCE MSO_STORE_TREND_ID_SEQ
START WITH     90000001
INCREMENT BY   1
MAXVALUE 95000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_GROUP_TREND
    Column_name:MSO_GROUP_TREND_ID
    Sequence to auto increment MSO_GROUP_TREND_ID Column   */

CREATE SEQUENCE MSO_GROUP_TREND_ID_SEQ
START WITH     95000001
INCREMENT BY   1
MAXVALUE 100000000
NOCACHE
NOCYCLE;






/* Table_Name:MSO_PROJ
    Column_name:MSO_PROJ_ID
    Sequence to auto increment MSO_GROUP_TREND_ID Column   */

CREATE SEQUENCE MSO_PROJ_ID_SEQ
START WITH     100000001
INCREMENT BY   1
MAXVALUE 105000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_PROJ_DATA_REQ
    Column_name:MSO_PROJ_DATA_REQ_ID
    Sequence to auto increment MSO_PROJ_DATA_REQ_ID Column   */

CREATE SEQUENCE MSO_PROJ_DATA_REQ_ID_SEQ
START WITH     105000001
INCREMENT BY   1
MAXVALUE 110000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_FCT_CLS_ARR_OPS_DEPT
    Column_name:FCT_CLS_ARR_ID
    Sequence to auto increment FCT_CLS_ARR_ID Column   */

CREATE SEQUENCE FCT_CLS_ARR_ID_SEQ
START WITH     110000001
INCREMENT BY   1
MAXVALUE 115000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_FCT_FOOTAGE_BENEFIT_STR_DE
    Column_name:FCT_FTAGE_BEN_STR_DEP_ID
    Sequence to auto increment FCT_FTAGE_BEN_STR_DEP_ID Column   */

CREATE SEQUENCE FCT_FTAGE_BEN_STR_DEP_ID_SEQ
START WITH     115000001
INCREMENT BY   1
MAXVALUE 120000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_FCT_SPACE_VOL_STR
    Column_name:FCT_SPACE_VOL_STR_ID
    Sequence to auto increment FCT_SPACE_VOL_STR_ID Column   */

CREATE SEQUENCE FCT_SPACE_VOL_STR_ID_SEQ
START WITH     120000001
INCREMENT BY   1
MAXVALUE 125000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_OPTIMIZER_RESULTS
    Column_name:OPTIMIZE_RESULT_ID
    Sequence to auto increment OPTIMIZE_RESULT_ID Column   */

CREATE SEQUENCE OPTIMIZE_RESULT_ID_SEQ
START WITH     125000001
INCREMENT BY   1
MAXVALUE 130000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_STORE_PRODUCTIVITY_MAP
    Column_name:MSO_STORE_PRODUCTIVITY_MAP_ID
    Sequence to auto increment MSO_STORE_PRODUCTIVITY_MAP_ID Column   */

CREATE SEQUENCE MSO_STORE_PRODUCT_SEQ
START WITH     135000001
INCREMENT BY   1
MAXVALUE 140000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_BATCH_WRAPPER_DETL
    Column_name:MSO_BATCH_WRAP_DETL_ID
    Sequence to auto increment MSO_BATCH_WRAP_DETL_ID Column   */


CREATE SEQUENCE MSO_BATCH_WRAP_DETL_ID_SEQ
START WITH     140000001
INCREMENT BY   1
MAXVALUE 145000000
NOCACHE
NOCYCLE;
/* Table_Name:MSO_STATUS_MASTER
    Column_name:STATUS_ID
    Sequence to auto increment STATUS_ID Column   */

CREATE SEQUENCE STATUS_ID_SEQ
START WITH     145000001
INCREMENT BY   1
MAXVALUE 150000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_STORE_DEPT_CONST_RULES
    Column_name:DEPT_CONST_STORE_RULE_ID
    Sequence to auto increment DEPT_CONST_STORE_RULE_ID Column   */

CREATE SEQUENCE DEPT_CONST_STORE_RULE_ID_SEQ
START WITH     150000001
INCREMENT BY   1
MAXVALUE 155000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_STORE_FIXT_COMPBTY
    Column_name:STORE_FIX_COMPBTY_RULE_ID
    Sequence to auto increment STORE_FIX_COMPBTY_RULE_ID Column   */
CREATE SEQUENCE STORE_FIX_COMPBTY_RULE_ID_SEQ
START WITH     155000001
INCREMENT BY   1
MAXVALUE 160000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_STORE_FIXT_RULES
    Column_name:FIX_STORE_RULE_ID
    Sequence to auto increment FIX_STORE_RULE_ID Column   */


CREATE SEQUENCE FIX_STORE_RULE_ID_SEQ
START WITH     160000001
INCREMENT BY   1
MAXVALUE 165000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_STORE_SHARED_FIXT_RULES
    Column_name:SHARED_FIX_STORE_RULE_ID
    Sequence to auto increment SHARED_FIX_STORE_RULE_ID Column   */


CREATE SEQUENCE SHARED_FIX_STORE_RULE_ID_SEQ
START WITH     165000001
INCREMENT BY   1
MAXVALUE 170000000
NOCACHE
NOCYCLE;
/* Table_Name:MSO_SEGMENT_MASTER
    Column_name:SEGMENT_MAST_ID
    Sequence to auto increment SEGMENT_MAST_ID Column   */


CREATE SEQUENCE SEGMENT_MAST_ID_SEQ
START WITH     175000001
INCREMENT BY   1
MAXVALUE 180000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_HALLMARK_FOOTAGE
    Column_name:HALLMRK_FOOTAGE_ID
    Sequence to auto increment HALLMRK_FOOTAGE_ID Column   */
CREATE SEQUENCE HALLMRK_FTAGE_ID_SEQ
START WITH     190000001
INCREMENT BY   1
MAXVALUE 195000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_OPTIMIZER_GEN2_RESULTS
    Column_name:OPTIMIZE_GEN2_RESULT_ID
    Sequence to auto increment OPTIMIZE_GEN2_RESULT_ID   */
CREATE SEQUENCE OPTIMIZE_GEN2_RESULT_ID_SEQ
START WITH     196000001
INCREMENT BY   1
MAXVALUE 197000000
NOCACHE
NOCYCLE;

/* Table_Name:MSO_DATA_REQ_CFW
    Column_name:MSO_DATA_REQ_CFW_ID
    Sequence to auto increment MSO_DATA_REQ_CFW_ID Column   */
CREATE SEQUENCE MSO_DATA_REQ_CFW_ID_SEQ
START WITH     196000001
INCREMENT BY   1
MAXVALUE 197000000
NOCACHE
NOCYCLE;


/* Table_Name:MSO_STORE_SEGMENT_MAP
    Column_name:STORE_SEGMENT_MAP_ID
    Sequence to auto increment STORE_SEGMENT_MAP_ID Column   */
CREATE SEQUENCE STORE_SEGMENT_MAP_ID_SEQ
START WITH     197000001
INCREMENT BY   1
MAXVALUE 198000001
NOCACHE
